language: java
before_install:
  - if [ -e $JAVA_HOME/lib/security/cacerts ]; then ln -sf /etc/ssl/certs/java/cacerts $JAVA_HOME/lib/security/cacerts; fi
install: true
script: mvn -B -s .travis-settings.xml -Prelease -Dgpg.skip=true verify
before_cache: "find $HOME/.m2 -name '*-SNAPSHOT' -a -type d -print0 | xargs -0 rm -rf"
jobs:
  include:
    - stage: test
      jdk: openjdk8
      # There are actually significant differences with respect to JMX in recent fix packs
      env: WEBSPHERE_VERSION=8.5.5.10
    - stage: test
      jdk: openjdk8
      env: WEBSPHERE_VERSION=8.5.5.14
    - stage: test
      jdk: openjdk8
      env: WEBSPHERE_VERSION=9.0.0.9
    - stage: test
      jdk: openjdk9
      env: WEBSPHERE_VERSION=8.5.5.14
    - stage: test
      jdk: openjdk10
      env: WEBSPHERE_VERSION=8.5.5.14
    - stage: test
      jdk: openjdk11
      env: WEBSPHERE_VERSION=8.5.5.14
    - if: repo = "veithen/visualwas" AND branch = master AND type = push
      stage: deploy
      jdk: openjdk8
      # Can't activate the release profile here because github-release-plugin can't be easily skipped
      script: mvn -B -s .travis-settings.xml -DskipTests=true deploy
      env:
        - secure: "j4g/eEJDnrMiFYm6DIrIf70FAlNaidJTG99wb/LY+FO0uIguFGHD33UDG0zxrSc/YG8biSfr/vO4oXM2qJcRkUiQkCfS3qNL2jD2/cmxOjsypi8Qzh4x9J5WQR1zU3PT4sSfeLyYK4Gbb0kPni4EpRkR6pcrwjcornJHUBLzis4="
cache:
  directories:
    - $HOME/.m2
